# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C9y3iEmw4tq7yMZ4HR-focEA3kvH8bDj
"""

import numpy as np
import math
import matplotlib.pyplot as plt
def generate1():  
    a = np.random.uniform(0,1)
    b = np.random.uniform(0,1)  
    return a * math.cos(2 * math.pi * b), a * math.sin(2 * math.pi * b)
b = np.random.uniform(0,1)  
n = 1000
#print(math.cos(2 * math.pi * b))
#print(generate1())
#s = np.random.uniform(-1,0,1000)
a = [[0.0]*2]*n
b = [0.0]*n
c = [0.0]*n
for i in range (0,n):
  a[i] = generate1()
  b[i] = a[i][0]
  c[i] = a[i][1]
#a.plot(x='date', y='like')
print(c)
#plt.show()
plt.scatter(b,c)
count = 0
for i in range (0,n):
  if (b[i]*b[i] + c[i]*c[i] >= 0.9):
    count= count + 1
count
print(count/n)

import numpy as np
import math
import matplotlib.pyplot as plt
def generate2():  
    while True:  
        x = np.random.uniform(-1, 1)  
        y = np.random.uniform(-1, 1)  
        if x ** 2 + y ** 2 > 1:  
            continue  
        return (x, y)
b = np.random.uniform(0,1)  
#print(math.cos(2 * math.pi * b))
#print(generate1())
#s = np.random.uniform(-1,0,1000)
a = [[0.0]*2]*1000
b = [0.0]*1000
c = [0.0]*1000
for i in range (0,1000):
  a[i] = generate2()
  b[i] = a[i][0]
  c[i] = a[i][1]
#a.plot(x='date', y='like')
print(c)
#plt.show()
plt.scatter(b,c)
count = 0
for i in range (0,n):
  if (b[i]*b[i] + c[i]*c[i] >= 0.9):
    count= count + 1
count

for i in range (0, 1000):
  print(f'{a[i][0]}' ' ' f'{a[i][1]}')

for i in range(0, 100):
  insrt = input()
  listRes = list(insrt.split(" "))
  count = 0
  for j in range(0, 1000):
    chet = float(listRes[2*j])
    nech = float(listRes[2*j+1])
    if (chet*chet + nech*nech > 0.9):
      count+=1
  if (count/1000 >= 0.08):
    print(2)
  else:
    print(1)

fib1 = fib2 = 1
 
n = int(input())
 
print(fib1, fib2, end=' ')
 
for i in range(2, n):
    fib1, fib2 = fib2, fib1 + fib2
    print(fib2, end=' ')
