# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C9y3iEmw4tq7yMZ4HR-focEA3kvH8bDj
"""

fib1 = 0
fib2 = 1
n = int(input())
  
print(fib1, fib2, end=' ')
sum = 0
#k * (S(k-1) - (k-1)) * 2^(-k)
for k in range(2, n):
    fib1, fib2 = fib2, fib1 + fib2
    sum += k * (fib1- (k-1)) * 2**(-k)
    #print(1*2**(-k))
    #print(fib2, end=' ')
sum

